apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-realm-config
  labels:
    app: keycloak
data:
  car-rental-realm.json: |
    {
      "id": "car-rental",
      "realm": "car-rental",
      "enabled": true,
      "users": [
        {
          "username": "test",
          "enabled": true,
          "credentials": [
            {
              "type": "password",
              "value": "test"
            }
          ],
          "realmRoles": [ "user" ],
          "clientRoles": {
            "rental-client": ["user"]
          }
        }
      ],
      "clients": [
        {
          "clientId": "rental-client",
          "enabled": true,
          "publicClient": false,
          "secret": "my-super-secret",
          "directAccessGrantsEnabled": true,
          "standardFlowEnabled": true,
          "authorizationServicesEnabled": true,
          "redirectUris": ["*"]
        }
      ]
    }